defaults:
  - data: finedance
  - defaults
  - _self_

data:
  preload: false
  motion_loader:
    normalizer:
      disable: true
  
  jukebox_feats_dir: ../datasets/finedance/fd_music_wav_checked_partation_jukebox
  music_token_feats_dir: ../datasets/finedance/fd_music_feats_clap_token
  music_sent_feats_dir: ../datasets/finedance/fd_music_feats_clap_sent

  # text_to_token_emb:
  #   disable: true
  # text_to_sent_emb:
  #   disable: true
