#!/usr/bin/env bash

RESEARCHWY_ROOT="${RESEARCHWY_ROOT:-/data/Life Me/Obsidian Respository/ResearchWY}"
LINKED_CODEBASES_DIR="${LINKED_CODEBASES_DIR:-${RESEARCHWY_ROOT}/linkedCodebases}"
MOTIONPATCHES_DIR="${MOTIONPATCHES_DIR:-${LINKED_CODEBASES_DIR}/MotionPatches-main}"
EVENTT2M_DIR="${EVENTT2M_DIR:-${LINKED_CODEBASES_DIR}/EventT2M-codes-main}"
